name: Run Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  release:
    types: [published]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.x, pypy3.10]
        exclude:
          # excludes pypy 3 on Windows
          - os: windows-latest
            python-version: pypy3.10
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run Unit Tests
        run: python -m pytest tests --doctest-modules --junitxml=test-results/test-results-${{ matrix.os }}-${{ matrix.python-version }}.xml
      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Results (${{ matrix.os }}, ${{ matrix.python-version }})
          path: test-results/test-results-${{ matrix.os }}-${{ matrix.python-version }}.xml

  event_file:
    name: Event File
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Event File
          path: ${{ github.event_path }}
