name: Run Unit Tests

on: [workflow_dispatch, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:               [windows-latest, ubuntu-latest]
        python-version:   [2.7, 3.x, pypy2, pypy3]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build pyxtuml
        run: python setup.py build
      - name: Run tests
        run: pytest tests --doctest-modules --junitxml=test-results/test-results-${{ matrix.python-version }}.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-results/**/*.xml
